### ISSUE TITLE
Enhance preview snippet

### ISSUE THREAD

**Issue by tvjames2007** [hteumeuleu/caniemail#105]
It would be nice to see more customized preview snippet that gives you a small bit of info when you share a unique link.  Something I shared recently:
![image](https://user-images.githubusercontent.com/950657/95496627-f1e32f00-0955-11eb-9b2a-6f184ce7114b.png)

**Comment by hteumeuleu** [comment]
This is a very good request. The proper way to share links like this would be to share the actual feature pages (https://www.caniemail.com/features/css-at-import/ and https://www.caniemail.com/features/html-link/), in which case you do get a proper dedicated text snippet. (And I'll be able to put a dedicated image once I'm done with the embed feature.) 

Unfortunately, however, since the search page is only generated client side, there’s no way for me to have proper infos for sharing on the search page. This would need to be done server side and require a whole new site architecture.

**Comment by hteumeuleu** [comment]
I'm closing this for now as there isn't much I can do. Feel free to reopen if you've got any guidance on how to set this up on a static site like caniemail.
