### ISSUE TITLE
Consider removing www prefix

### ISSUE THREAD

**Issue by Marat-Tanalin** [hteumeuleu/caniemail#152]
The `www` prefix generally does not make sense and just unreasonably makes URLs 4-character longer, unless you intend to add subdomains and want to isolate the main-site cookies from those subdomains.

Compare:

    https://www.caniemail.com/features/css-function-min/
    https://caniemail.com/features/css-function-min/

GitHub, CanIUse and CSS-Tricks are examples of www-free sites. Best regards.

**Comment by hteumeuleu** [comment]
Hello there,

Thanks for your feedback. I've been thinking about this since you posted this issue, but I think I'll pass.

First, I indeed use the [embed.caniemail.com](https://embed.caniemail.com) subdomain which I'd like to keep cookies free.

And then, more important, removing the `www` prefix would require to create a 301 redirection for every existing URL. But the site is currently hosted by GitHub Pages which has no support to such a feature, so this would require me to change host (and probably a paid one). Overall, this seems like at least a 2 days task for a barely considerable improvement. I can see why GitHub, Twitter or other sites with massive traffic would opt for this. But on the scale of caniemail, that seems unnecessary.

Plus, as a purely personal preference, I really like having the `www` in the URL. 

I'm closing this for now. But if anyone has better arguments for this, let me know.
