### ISSUE TITLE
Feature request: text/html support

### ISSUE THREAD

**Issue by mkalam-alami** [hteumeuleu/caniemail#195]
This may be a dumb request, but I have no idea what the market share is for clients that only support `text/plain` emails (ie. no HTML at all). I don't know if their share is negligible (all listed clients seem to support it) or if they are just out of scope for this website.

Having "text/html content type support" listed as a feature, with maybe a short comment about the subject would be valuable information to me.

Note: For the sake of completeness, my issue is I have found a bug in the `text/plain` version of an email, although there is also a main, `text/html` one sent simultaneously. I would like to gauge the criticity of that problem by knowing how widespread are `text/plain` only clients.

**Comment by hteumeuleu** [comment]
Hey there, thanks for your suggestion. I'm not sure I entirely follow. Can I email is focused on listing support for HTML or CSS features, so this means that all clients currently tested on the site do support `text/html`. There's no plan to add clients that do no support HTML emails since they would report "Unsupported" for all features. I think pretty much all the clients listed on Can I email support showing plain text email only. You can visit the website https://useplaintext.email/ for a list of a few plain text only email clients.

**Comment by mkalam-alami** [comment]
Ah I thought I had answered but didn't. 

Thanks for your response, my request seems out of scope indeed and the link to useplaintext.email was helpful :)
