### ISSUE TITLE
Add in fonts that work across platforms

### ISSUE THREAD

**Issue by thommeredith** [hteumeuleu/caniemail#405]
If I search for Arial Black, I can see which platforms should support that font.

**Comment by husseinalhammad** [comment]
This is not email-specific, but OS-specific. A system font may be available on a webmail on Windows, but not on MacOS.

**Comment by hteumeuleu** [comment]
I love the idea, but yeah, I think that should be an entire project of its own. (Can I type?) I'm closing this as I don't think caniemail is the place for this.

**Comment by kcrwfrd** [comment]
A guide of email-safe fonts (something like https://templates.mailchimp.com/design/typography/, except with examples shown, kind of like https://www.w3schools.com/cssref/css_websafe_fonts.php) would be extremely helpful to have. Every time a designer hands over an email design, explaining all of the constraints is a challenge, and font selection is a massive part of that.

I agree that such a guide doesn't quite fit in with the design of the feature support tables on caniemail.com... Like I guess you could think of it like image formats: https://www.caniemail.com/search/?s=image%20format, but the information is a little verbose, and lacks the visual example of the font.

I would urge consideration for a separate tab for an email safe font guide, because caniemail.com is the de facto best resource on the web for navigating HTML email support, and while it is slightly tangential it's also a very pertinent question that comes up in the course of implementing HTML emails.

**Comment by husseinalhammad** [comment]
Are you looking for something like these?

- https://www.cssfontstack.com/
- https://web.mit.edu/jmorzins/www/fonts.html

These don't include some operating systems like Android, HarmonyOS (Huawei) and Linux.

**Comment by hteumeuleu** [comment]
Looks like there's a project coming for this: [Which local fonts can I use?](https://highperformancewebfonts.com/read/which-local-fonts-can-I-use) You can help by visiting https://fontes-locais.vercel.app/ in Chrome and it will report the fonts installed in your OS using Chrome's `FontFace` API.
