### ISSUE TITLE
Outlook on platform Windows supports svg-image

### ISSUE THREAD

**Issue by TylerBurnett** [hteumeuleu/caniemail#468]
Both Outlook (new) and their legacy version support SVG images

**My Outlook(Classic) version details:**
Microsoft® Outlook® for Microsoft 365 MSO (Version 2407 Build 16.0.17830.20210) 64-bit 

There is a caveat, that is that outlook does not automatically download the images in the older version, it also does a poor job of scaling the SVG with certain dimensions.

**My Outlook(New) version details:**
You have Microsoft Outlook Version 1.2024.925.200 (Production).
Client Version is 20240920004.10.
WebView2 Version is 129.0.2792.65.

**Comment by hteumeuleu** [comment]
Do you have any test code?

**Comment by TylerBurnett** [comment]
By test code do you mean an example email that currently works? I believe this HTML content would be sufficient 
https://github.com/hteumeuleu/caniemail/blob/main/tests/images.html

**Comment by hteumeuleu** [comment]
Alright, I see this working in Outlook version 2408 (Build 17928.20114) (Legacy version, using Word’s rendering engine). 

![A screenshot of the email showing an svg img displayed in Outlook on Windows.](https://github.com/user-attachments/assets/2fefd53c-c03b-4c5f-b742-9b166177ebb9)

As for the new Outlook, I haven't retested it right now but it makes sense as it's supported by other Outlook versions (and the point of the new Outlook is to streamline HTML and CSS support across every Outlook). However, because it's such a major change, and still in beta, we'll push a separate update for this later on. (Previously started in `data/outlook-one`, but that was so long ago I'd probably start over https://github.com/hteumeuleu/caniemail/tree/data/outlook-one).
