### ISSUE TITLE
Yahoo! Desktop Webmail seems to no longer support form submission

### ISSUE THREAD

**Issue by eckstein** [hteumeuleu/caniemail#469]
The [table indicates](https://www.caniemail.com/features/html-form/) Yahoo! supports form and input elements, but I'm having trouble replicating that. If I don't include a `<form>` element the form doesn't submit (expected) but if I do include a form element, Yahoo! seems to auto-close it before the first input.

So, this:
```
<form>
<input>
<submit>
</form>
```

Turns into this:
```
<form></form>
<input>
<submit>
```

**Comment by eckstein** [comment]
I did some more experimenting here and figured out this was caused by a misplaced closing tag in the wrapping HTML. Essentially, a `<div>` ended up between a `<tr>` and a `<td>` which didn't cause any visual issues, but did cause this strange bug. Probably not worth mentioning on the chart, but maybe something will find this useful someday.

**Comment by hteumeuleu** [comment]
Thanks for reporting this. I'm closing it because I wouldn't qualify this as a caniemail bug. However, it might be interesting to open a thread on [email-bugs](https://github.com/hteumeuleu/email-bugs/issues). I don't think there's much litterature about email clients parsing malformed HTML and I think it's a very interesting topic.
